name: Feature Request
description: 新機能のリクエスト
title: "[要望]: "
labels: ["enhancement", "Needs Triage"]
assignees:
  - Mogyuchi

body:
  - type: textarea
    id: request
    attributes:
      label: リクエスト
      description: 追加したい機能について説明してください。
    validations:
      required: true

  - type: markdown
    attributes:
      value: "ご記入ありがとうございました"
