name: 開発者体験の向上
description: ウェブページに直接影響しないものはこちら
labels: ["for develop", "Needs Triage"]
title: "[DX]: "
assignees:
  - Mogyuchi
body:
  - type: textarea
    id: improvement_target
    attributes:
      label: 改善対象の事柄
      description: 簡潔に記述してください。
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: 期待する挙動
      description: 改善後に期待する挙動を簡潔に記述してください。
    validations:
      required: true
  - type: textarea
    id: supplementary-information
    attributes:
      label: 補足情報
      description: |
        さらなる情報や詳しく説明したいことがありましたらこちらへ。
    validations:
      required: false

  - type: markdown
    attributes:
      value: "ご記入ありがとうございました"
