name: Auto PR

on:
  create

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - run: cat $GITHUB_EVENT_PATH
      - run: gh --version
      - run: docker --version
      - run: docker-compose --version
  pr:
    if: github.event.ref_type == 'branch'
    name: Create PR
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Create a pull request
        run: |
          ISSUE=`echo ${{ github.event.ref }} | grep -oE '#[0-9]+'`
          gh pr create --draft --base develop --assignee ${{ github.event.sender.login }} --title ${{ github.event.ref }} --body "close $ISSUE $(false)"
