name: souji
on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      # https://docs.github.com/en/rest/actions/cache?apiVersion=2022-11-28#delete-a-github-actions-cache-for-a-repository-using-a-cache-id
      actions: write
    steps:
      - name: Cleanup
        uses: 4m-mazi/souji-action@94624a10c15873dcb8b136646229c09ba1114502
