name: souji
on:
  pull_request:
    types:
      - closed
  workflow_dispatch:
  push:
    branches: "**"

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      # https://docs.github.com/en/rest/actions/cache?apiVersion=2022-11-28#delete-a-github-actions-cache-for-a-repository-using-a-cache-id
      actions: write
    steps:
      - name: Cleanup
        uses: 4m-mazi/souji-action@e7e91fdc79120b19d7ed8e5ad7f37197ec86c35e
