name: cleanup caches by a branch
on:
  pull_request_target:
    types:
      - closed
  delete:
  workflow_dispatch:
    inputs:
      branchNames:
        description: 'List of branch(ref) names with caches to be deleted'
        required: false
        type: string

jobs:
  cleanup:
    permissions:
      actions: write
      contents: read
    uses: 4m-mazi/souji-action/.github/workflows/_souji.yml@987bf7f5f3933a0392139c559147bba5a89a63d7 # v1.4.10
    with:
      branch-names: ${{ inputs.branchNames }}
