name: Fallback pr create
on:
  pull_request:
  issue_comment:
  pull_request_review:
  pull_request_review_comment:

jobs:
  approved:
    name: '!!!'
    if:  ${{ !github.event.issue || github.event.issue.pull_request }}
    runs-on: ubuntu-22.04
    steps:
      - run: "true"
