name: Fix branch

on:
  pull_request_target:
    types:
      - opened
      - reopened
    branches:
      - "main"
      - "develop"

permissions:
  pull-requests: write

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -xe {0}
    steps:
      - run: echo ${{ github.event.commits[0].url }} >> $GITHUB_STEP_SUMMARY
      - run: |
          echo "GITHUB_EVENT_PATH
          \`\`\`json
          `cat $GITHUB_EVENT_PATH`
          \`\`\`" >> $GITHUB_STEP_SUMMARY
      - run: |
          echo "gh
          \`\`\`console
          `gh --version`
          \`\`\`" >> $GITHUB_STEP_SUMMARY
      - run: |
          echo "docker
          \`\`\`console
          `docker --version`
          \`\`\`" >> $GITHUB_STEP_SUMMARY
      - run: |
          echo "docker-compose
          \`\`\`console
          `docker-compose --version`
          \`\`\`" >> $GITHUB_STEP_SUMMARY
      - run: |
          echo 'github context
          ```json
          ${{ toJSON(github) }}
          ```' >> $GITHUB_STEP_SUMMARY
  change-base_branch:
    name: Change base branch
    if: |
      ( github.base_ref == 'develop' && ( startsWith(github.head_ref, 'hotfix/') || startsWith(github.head_ref, 'release/') ) )
      || ( github.base_ref == 'main' && ! ( startsWith(github.head_ref, 'hotfix/') || startsWith(github.head_ref, 'release/') || github.head_ref == 'develop' ) )
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -xe {0}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_REPO: ${{ github.repository }}
      PR_NUMBER: ${{ github.event.number }}
    steps:
      - run: |
          if ${{ github.base_ref == 'develop' }}; then
            gh pr edit $PR_NUMBER --base main
          else
            gh pr edit $PR_NUMBER --base develop
          fi
