name: Build patch.aul

on:
  push:
    branches:
      - patch.aul

jobs:
  build:
    name: Build patch.aul
    runs-on: windows-2022

    steps:
      - name: Checkout patch.aul
        uses: actions/checkout@v3
        with:
          repository: hiraginoyuki/patch.aul

      - name: Setup MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@1
        with:
          toolkit: 19.31

      - name: Install CUDA toolkit
        id: cuda-toolkit
        uses: Jimver/cuda-toolkit@v0.2.7

      - name: Echo cuda toolkit location
        run: echo "Version: ${{ steps.cuda-toolkit.outputs.cuda }}\nCUDA_PATH: ${{ steps.cuda-toolkit.outputs.CUDA_PATH }}"
