name: "publish crates"
on:
  push:
    branches: ["**"]
  pull_request:
  workflow_call:
    inputs: # null for another event
      dry-run:
        type: boolean
        default: true

permissions: {}

jobs:
  set-up:
    if: ${{ !( toJSON(inputs) == '{}' && startsWith(github.event.head_commit.message, 'release:') ) }}
    runs-on: ubuntu-latest
    permissions: {}
    outputs:
      dry-run: ${{ steps.set-dry-run.outputs.dry-run }}
    steps:
      - id: set-dry-run
        env:
          DRY_RUN: ${{ toJSON(inputs) == '{}' || inputs.dry-run == true }}
        run: echo "dry-run=$DRY_RUN" >> $GITHUB_OUTPUT
  publish:
    needs: ["set-up"]
    name: "${{ fromJson(needs.set-up.outputs.dry-run) && 'DRY-RUN' || '' }} publish"
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          filter: tree:0
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

          DRY_RUN: ${{ true && '--dry-run' || '' }} # true -> fromJson(needs.set-up.outputs.dry-run)
        run: |
          cargo publish --all-features "$DRY_RUN"
