name: publish crates
on:
  push:
    branches: ["**"]
  pull_request:
  workflow_call:

permissions: {}

jobs:
  publish:
    if: ${{ !( github.workflow == 'crates publish' && startsWith(github.event.head_commit.message, 'release:') && github.event.head_commit.author.name == 'github-actions[bot]' ) }}
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          dry-run: ${{ true || github.workflow == 'publish crates' }}
          ignore-unpublished-changes: true
