on:
  push:
    branches:
      - main

name: release-please

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_REPO: ${{ github.repository }}

jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      pr: ${{ steps.release.outputs.pr }}
    steps:
      - uses: google-github-actions/release-please-action@8016a6649226f2ec88ed05441c11bb5410a22d29 # v3.7.10
        id: release
        with:
          release-type: rust
    ### マージしたあと、pushイベントが発火しないのでダメ
    # - if: ${{ steps.release.outputs.pr }}
    #   name: Enable auto merge
    #   run: gh pr merge ${{ fromJSON(steps.release.outputs.pr).number }} --auto --delete-branch --squash
  build:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    permissions:
      contents: write
      packages: write
    uses: ./.github/workflows/build.yml
    with:
      tag-name: ${{ needs.release-please.outputs.tag_name }}

  post-release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh label create 'autorelease: published' --color ededed || :
          pr_number=$(printf '${{ github.event.head_commit.message }}' | head -n1 | sed -nE 's/.+\(#([0-9]+)\)$/\1/p')
          gh pr edit "$pr_number" \
          --remove-label 'autorelease: tagged' \
          --add-label 'autorelease: published'
