name: Resources

on:
  push:

  workflow_dispatch:

jobs:
  resources:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git config --global push.default current
      - name: Commit
        run: |
          ls -a | grep -vE '^(.|..|.git|public)$' | xargs git rm -rf
          git add .
          git commit -m "Extract public/ from ${GITHUB_SHA}"
          git switch resources || git switch -c resources
          git merge -Xtheirs @{-1} --no-ff --no-edit
      - name: Push
        run: git push
