name: test
on:
  workflow_dispatch:
    inputs: # null for another event
      skip:
        type: choice
        default: no
        options:
          - no
          - workflow
          - job
permissions: {}

concurrency:
  group: ${{ github.workflow }}-workflow
  cancel-in-progress: ${{ inputs.skip != 'job' }}

jobs:
  test1:
    if: ${{ inputs.skip == 'false'}}
    runs-on: ubuntu-latest
    steps:
      - run: sleep 60
  test2:
    concurrency:
      group: ${{ github.workflow }}-job
      cancel-in-progress: true
    if: ${{ inputs.skip != 'job'}}
    runs-on: ubuntu-latest
    steps:
      - run: sleep 120
