on:
  push:
    branches: ["**"]

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ !startsWith(github.event.head_commit.message, 'chore(main)')}}
        run: echo "${{ !startsWith(github.event.head_commit.message, 'chore(main)')}}" >> $GITHUB_STEP_SUMMARY
  call-test:
    uses: ./.github/workflows/debug.yml
