on:
  push:
    branches: ["**"]

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - if: false
        run: echo "test" >> $GITHUB_STEP_SUMMARY
  call-test:
    uses: ./.github/workflows/debug.yml
