name: test
on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:
    inputs: # null for another event
      skip:
        type: boolean
        default: false
permissions: {}

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
        continue-on-error: true
      - run: exit 1
        continue-on-error: true
      - run: exit 1
        continue-on-error: true
  test2:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
        continue-on-error: true
      - run: exit 1
        continue-on-error: true
      - run: exit 0
  test3:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://mikefarah/yq:4.44.1-githubaction@sha256:ecec8897cfc63329efa97179e4ddc5b2b571ab19dce13c98988fbca5fc778127
        continue-on-error: true
      - uses: goto-bus-stop/setup-zig@v2
      
      - id: step1
        run: exit 0
        continue-on-error: true
      - id: step2
        run: exit 0
        continue-on-error: true
      - if: contains(steps.*.outcome, 'failure')
        run: exit 1
