name: test
on:
  workflow_dispatch:
    inputs: # null for another event
      skip:
        type: boolean
        default: false
permissions: {}

jobs:
  test1:
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true
    if: ${{ inputs.skip == false}}
    runs-on: ubuntu-latest
    steps:
      - run: sleep 120
