name: test
on:
  push:
    branches: ["**"]

permissions: {}

jobs:
  test1:
    if: true # test
    runs-on: ubuntu-latest
    steps:
      - run: |
          cat << 'EOF' >> $GITHUB_STEP_SUMMARY
          inputs
          ```json
          ${{ toJSON(inputs) }}
          ```
          ${{ toJSON(inputs) == '{}' }}
          EOF
  test2:
    if: ${{ !startsWith(github.event.head_commit.message, 'chore(main):\ ')}}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "test2: ${{ !startsWith(github.event.head_commit.message, 'chore(main)')}}" >> $GITHUB_STEP_SUMMARY
  test3:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "test3: ${{ false == null }}" >> $GITHUB_STEP_SUMMARY

  call-test:
    uses: ./.github/workflows/debug.yml
