name: test
on:
  push:
    branches: ["**"]

permissions: write-all

jobs:
  test1:
    if: ${{ !startsWith(github.event.head_commit.message, 'release:')}}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "test1: ${{ !startsWith(github.event.head_commit.message, 'chore(main)')}}" >> $GITHUB_STEP_SUMMARY
  test2:
    if: ${{ !startsWith(github.event.head_commit.message, 'chore(main):\ ')}}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "test2: ${{ !startsWith(github.event.head_commit.message, 'chore(main)')}}" >> $GITHUB_STEP_SUMMARY

  call-test:
    uses: ./.github/workflows/debug.yml

  sshx:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - run: sleep 10
      - run: sleep 10
      - run: curl -sSf https://sshx.io/get | sh && sshx
