name: test
on:
  push:
    branches: ["**"]

permissions: {}

jobs:
  test1:
    if: ${{ startsWith(github.event.head_commit.message, 'release:')}}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "`startsWith(github.event.head_commit.message, 'release:')`: ${{ startsWith(github.event.head_commit.message, 'release:')}}" >> $GITHUB_STEP_SUMMARY
      - run: |
          echo "`github.event.head_commit.author.name == 'github-actions[bot]'`: ${{ github.event.head_commit.author.name == 'github-actions[bot]'}}" >> $GITHUB_STEP_SUMMARY
  test2:
    if: ${{ !startsWith(github.event.head_commit.message, 'chore(main):\ ')}}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "test2: ${{ !startsWith(github.event.head_commit.message, 'chore(main)')}}" >> $GITHUB_STEP_SUMMARY
  test3:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "test3: ${{ false == null }}" >> $GITHUB_STEP_SUMMARY

  call-test:
    uses: ./.github/workflows/debug.yml
