name: test
on:
  workflow_dispatch:
    inputs: # null for another event
      skip:
        type: boolean
        default: false
permissions: {}

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test1:
    if: ${{ inputs.skip == false}}
    runs-on: ubuntu-latest
    steps:
      - run: sleep 60
