name: test
on:
  push:
    branches: ["**"]
  workflow_dispatch:
    inputs: # null for another event
      skip:
        type: boolean
        default: false
permissions: {}

jobs:
  test1:
    if: >
      false
    runs-on: ubuntu-latest
    steps:
      - run: |
          true
  test2:
    if: >-
      false
    runs-on: ubuntu-latest
    steps:
      - run: |
          true
