name: trigger Renovate
on:
  issues:
    # Dependency Dashboard
    types: [edited]
  pull_request_target:
    types:
      # rebaseLabel
      - labeled
      # stopUpdatingLabel
      - unlabeled
      # PrControls
      - edited
      # ignore update
      - closed
      # Edited/Blocked
      - synchronize
    branches: ["main"]
  push:
    branches:
      - "main"
      # https://docs.renovatebot.com/config-validation/#validation-of-renovate-config-change-prs
      - "renovate/reconfigure"
  schedule:
    # Run every 30 minutes:
    - cron: "0,30 * * * *"
  # This lets you dispatch a renovate job with different cache options if you want to reset or disable the cache manually.
  workflow_dispatch:
    inputs:
      repoCache:
        description: "Reset or disable the cache?"
        type: choice
        default: enabled
        options:
          - enabled
          - disabled
          - reset

permissions: {}

jobs:
  trigger-renovate:
    uses: 4m-mazi/gh-test/.github/workflows/_renovate.yml@main
    with:
      renovate_actor: "mazi-renovate[bot]"
      repoCache: ${{ inputs.repoCache }}
    secrets:
      app-id: ${{ vars.MAZI_RENOVATE_APP_ID }}
      private-key: ${{ secrets.MAZI_RENOVATE_PRIVATE_KEY }}
